/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthsiapsepControlCoverIndexRouteImport } from './routes/_auth/(siapsep)/controlCover/index'
import { Route as AuthsiapsepCaptureIndexRouteImport } from './routes/_auth/(siapsep)/capture/index'
import { Route as AuthkardexEmployeesIndexRouteImport } from './routes/_auth/(kardex)/employees/index'
import { Route as AuthconceptsRefundIndexRouteImport } from './routes/_auth/(concepts)/refund/index'
import { Route as AuthconceptsForteIndexRouteImport } from './routes/_auth/(concepts)/forte/index'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthsiapsepControlCoverIndexRoute =
  AuthsiapsepControlCoverIndexRouteImport.update({
    id: '/(siapsep)/controlCover/',
    path: '/controlCover/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthsiapsepCaptureIndexRoute = AuthsiapsepCaptureIndexRouteImport.update({
  id: '/(siapsep)/capture/',
  path: '/capture/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthkardexEmployeesIndexRoute =
  AuthkardexEmployeesIndexRouteImport.update({
    id: '/(kardex)/employees/',
    path: '/employees/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthconceptsRefundIndexRoute = AuthconceptsRefundIndexRouteImport.update({
  id: '/(concepts)/refund/',
  path: '/refund/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthconceptsForteIndexRoute = AuthconceptsForteIndexRouteImport.update({
  id: '/(concepts)/forte/',
  path: '/forte/',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/signin': typeof SigninRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/forte/': typeof AuthconceptsForteIndexRoute
  '/refund/': typeof AuthconceptsRefundIndexRoute
  '/employees/': typeof AuthkardexEmployeesIndexRoute
  '/capture/': typeof AuthsiapsepCaptureIndexRoute
  '/controlCover/': typeof AuthsiapsepControlCoverIndexRoute
}
export interface FileRoutesByTo {
  '/signin': typeof SigninRoute
  '/': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/forte': typeof AuthconceptsForteIndexRoute
  '/refund': typeof AuthconceptsRefundIndexRoute
  '/employees': typeof AuthkardexEmployeesIndexRoute
  '/capture': typeof AuthsiapsepCaptureIndexRoute
  '/controlCover': typeof AuthsiapsepControlCoverIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/signin': typeof SigninRoute
  '/_auth/': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/(concepts)/forte/': typeof AuthconceptsForteIndexRoute
  '/_auth/(concepts)/refund/': typeof AuthconceptsRefundIndexRoute
  '/_auth/(kardex)/employees/': typeof AuthkardexEmployeesIndexRoute
  '/_auth/(siapsep)/capture/': typeof AuthsiapsepCaptureIndexRoute
  '/_auth/(siapsep)/controlCover/': typeof AuthsiapsepControlCoverIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/api/auth/$'
    | '/forte/'
    | '/refund/'
    | '/employees/'
    | '/capture/'
    | '/controlCover/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/signin'
    | '/'
    | '/api/auth/$'
    | '/forte'
    | '/refund'
    | '/employees'
    | '/capture'
    | '/controlCover'
  id:
    | '__root__'
    | '/_auth'
    | '/signin'
    | '/_auth/'
    | '/api/auth/$'
    | '/_auth/(concepts)/forte/'
    | '/_auth/(concepts)/refund/'
    | '/_auth/(kardex)/employees/'
    | '/_auth/(siapsep)/capture/'
    | '/_auth/(siapsep)/controlCover/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  SigninRoute: typeof SigninRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/(siapsep)/controlCover/': {
      id: '/_auth/(siapsep)/controlCover/'
      path: '/controlCover'
      fullPath: '/controlCover/'
      preLoaderRoute: typeof AuthsiapsepControlCoverIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/(siapsep)/capture/': {
      id: '/_auth/(siapsep)/capture/'
      path: '/capture'
      fullPath: '/capture/'
      preLoaderRoute: typeof AuthsiapsepCaptureIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/(kardex)/employees/': {
      id: '/_auth/(kardex)/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof AuthkardexEmployeesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/(concepts)/refund/': {
      id: '/_auth/(concepts)/refund/'
      path: '/refund'
      fullPath: '/refund/'
      preLoaderRoute: typeof AuthconceptsRefundIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/(concepts)/forte/': {
      id: '/_auth/(concepts)/forte/'
      path: '/forte'
      fullPath: '/forte/'
      preLoaderRoute: typeof AuthconceptsForteIndexRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthconceptsForteIndexRoute: typeof AuthconceptsForteIndexRoute
  AuthconceptsRefundIndexRoute: typeof AuthconceptsRefundIndexRoute
  AuthkardexEmployeesIndexRoute: typeof AuthkardexEmployeesIndexRoute
  AuthsiapsepCaptureIndexRoute: typeof AuthsiapsepCaptureIndexRoute
  AuthsiapsepControlCoverIndexRoute: typeof AuthsiapsepControlCoverIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthconceptsForteIndexRoute: AuthconceptsForteIndexRoute,
  AuthconceptsRefundIndexRoute: AuthconceptsRefundIndexRoute,
  AuthkardexEmployeesIndexRoute: AuthkardexEmployeesIndexRoute,
  AuthsiapsepCaptureIndexRoute: AuthsiapsepCaptureIndexRoute,
  AuthsiapsepControlCoverIndexRoute: AuthsiapsepControlCoverIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  SigninRoute: SigninRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
